<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>An Analysis of Police Shootings in the United States from 2015-2021</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">The Wranglers</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">An Analysis of Police Shootings in the United States from 2015-2021</h1>
<p class="subtitle lead">Report</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="cell">

</div>
<p><strong>Introduction</strong></p>
<p>Created on September 15, 2021, the <code>police_shootings</code> data set is sourced from the CORGIS Dataset Project and was compiled from findings by <em>The Washington Post</em>. <em>The Washington Post</em> regularly collects this data as police shootings happen by monitoring local news reports, law enforcement websites, social media, and other independent databases such as Killed by Police and Fatal Encounters. When necessary, <em>The Post</em> also did additional research to investigate each individual case.</p>
<p>This data set describes fatal shootings by a police officer in the line of duty in the United States from January 1, 2015, to September 11, 2021. Each observation represents a single fatal shooting event by a police officer. This data includes information on the victim’s gender, race, mental illness, location, and date of the event.</p>
<p>In a <a href="https://www.nature.com/articles/d41586-019-02601-9"><em>Nature</em> article</a> titled “What the data say about police shootings,” Lynne Peeples explains that police officers in the United States fatally shoot roughly three people per day — a statistic that rivals the yearly totals of other comparable nations. Data on these tragic encounters is often limited, but in recent years newspapers, enterprising individuals, and the federal government have launched ambitious data-collection projects to fill the gaps and improve transparency and accountability over how police officers exercise their right to use deadly force. Researchers have posed many pressing questions, including whether the police are disproportionately quick to shoot Black and other minority civilians. That said, further exploration and analysis is desperately needed to brings awareness to implicit biases entrenched in the US police force and may suggest ways to build a better future for all citizens.</p>
<p><strong>Research question</strong></p>
<p>How do race, gender, age, and whether a civilian was armed or not affect the perceived threat level of a victim in fatal police shootings across the United States from 2015 to 2021?</p>
<p><strong>Data</strong></p>
<p>Our data set includes 6569 rows (observations), indicating that at least 6569 known people were killed by police from 2015 to 2021. By investigating how different factors affect the number of shootings across demographic groups, we can begin to understand why these tragedies happen and what we can do to stop them from happening going forward. Specifically, our research topic examines police shooting history on the basis of race, gender, and age. We hypothesize that male individuals who identify as a POC are more likely to be perceived as a threat by police during fatal shootings.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6,569
Columns: 16
$ Person.Name              &lt;chr&gt; "Tim Elliot", "Lewis Lee Lembke", "John Paul …
$ Person.Age               &lt;dbl&gt; 53, 47, 23, 32, 39, 18, 22, 35, 34, 47, 25, 3…
$ Person.Gender            &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male…
$ Person.Race              &lt;chr&gt; "Asian", "White", "Hispanic", "White", "Hispa…
$ Incident.Date.Month      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ Incident.Date.Day        &lt;dbl&gt; 2, 2, 3, 4, 4, 4, 5, 6, 6, 6, 6, 7, 7, 7, 7, …
$ Incident.Date.Year       &lt;dbl&gt; 2015, 2015, 2015, 2015, 2015, 2015, 2015, 201…
$ Incident.Date.Full       &lt;date&gt; 2015-01-02, 2015-01-02, 2015-01-03, 2015-01-…
$ Incident.Location.City   &lt;chr&gt; "Shelton", "Aloha", "Wichita", "San Francisco…
$ Incident.Location.State  &lt;chr&gt; "WA", "OR", "KS", "CA", "CO", "OK", "AZ", "KS…
$ Factors.Armed            &lt;chr&gt; "gun", "gun", "unarmed", "toy weapon", "nail …
$ `Factors.Mental-Illness` &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRU…
$ `Factors.Threat-Level`   &lt;chr&gt; "attack", "attack", "other", "attack", "attac…
$ Factors.Fleeing          &lt;chr&gt; "Not fleeing", "Not fleeing", "Not fleeing", …
$ Shooting.Manner          &lt;chr&gt; "shot", "shot", "shot and Tasered", "shot", "…
$ `Shooting.Body-Camera`   &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRU…</code></pre>
</div>
</div>
<p><strong>Ethical Concerns</strong></p>
<p>One ethical concern is the possibility of misinformation in the data and a lack of accurate reporting. Not every police shooting is reported or handled correctly. Although <em>The Washington Post</em> compiled the data from many different sources, this report has no way of verify that the data set is fully comprehensive of every fatal police shooting in the United States.</p>
<p>Second, as demonstrated below, all 6569 victims identified in this data set have been labeled as having a mental illness. As a result, we decide not to make a visualization based on the mental illness variable. Our team believes that mental health is a spectrum with varying characteristics and severity of impact and that reducing mental illness to a simple “TRUE” or “FALSE” characterization would be unethical. Instead, we will focus our report on other variables.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6569</code></pre>
</div>
</div>
<p>Finally, a third ethical concern is consent and whether the victims’ families want their loved ones to have identifying information (like name and details about their death) in a public database. This is a highly sensitive topic and our team seeks to treat it as such.</p>
<p>For the purposes of this project, we will assume that the following data was collected randomly and that observations are independent.</p>
<p>We have identified several key variables that will advance our research question:</p>
<p><code>Person.Age</code> - An integer value of the victim’s age</p>
<p><code>Person.Gender</code> - The victim’s identified gender</p>
<p><code>Person.Race</code> - The victim’s identified race</p>
<p><code>Incident.Location.State</code> - The state in which the shooting incident happened</p>
<p><code>Factors.Armed</code> - Indicates whether the victim was armed</p>
<p><code>Factors.Threat-Level</code> - The preceived level of threat of the victim according to police (classified as either “attack”, “undetermined”, “other”, or “unknown”)</p>
<p><strong>Methodology</strong></p>
<p>First, our research team conducted exploratory data analyses based on summary statistics. We found that the average age and media age for a police shooting victim in this data set are 35 years old and 34 years old, respectively. Moreover, the standard deviation of the victim’s age is roughly 15 years, indicating that this data set represents a broad sampling of fatal police shootings across age groups.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  mean_age median_age stdv_age
     &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;
1     35.4         34     14.9</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/usmap-shootings-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As evidenced by the map above, the majority of our data was collected in California. This fact could limit our ability to generalize conclusions from our analysis, as California may be overrepresented.</p>
<p>Next, we visualized the number of fatal police shootings per day across the seven years in our data set. We created a new variable <code>days_in_year</code> to that included the number of days in each year studied, accounting for leap years and the end of data collection in September 2021. Next, we chose to generate a line graph to represent the progression of shootings per day over time, as it effectively reveals trends and changes across the years. Overall, the daily shooting rates fluctuate between 2.45 and 2.8 shootings per day, with a slight dip in 2021 that may have been caused by the COVID-19 pandemic.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/yearly-analysis-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As seen by the graph below, ~10% of male victims and 13% of female victims were unarmed.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/arms-status-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Next, we used box plots to visualize the age of the victims based on race (Fig. 3) and sex (Fig.4). We chose this method of visualize to clearly compare the median, range, and outliers across demographic groups.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/box-plots-race-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/box-plot-gender-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Furthermore, we created a pie chart to visualize the racial composition of the victims represented in our data set. Based on the graphic below, we observed that the three most represented racial groups in this data set are people identified as white, African American, or unknown (to the data collectors).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/bar-graph-race-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In addition, we visualized the the proportion of victims that carried weapons or not based on race using a bar graph.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/bar-graph-arms-status-race-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Finally, we fit a <strong>logistic regression model</strong> to explore which variables best predicted the likelihood of a victim being perceived as a threat by police.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8485.761</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  term                      estimate std.error statistic  p.value
  &lt;chr&gt;                        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)               -0.229     0.138      -1.66  9.61e- 2
2 raceWhite                 -0.114     0.0539     -2.12  3.38e- 2
3 Person.GenderMale         -0.245     0.123      -1.98  4.74e- 2
4 Person.GenderUnknown       1.04      1.23        0.843 3.99e- 1
5 Factors.Armed.Testunarmed  0.653     0.0835      7.81  5.66e-15
6 Person.Age                -0.00419   0.00180    -2.33  1.98e- 2</code></pre>
</div>
</div>
<p><span class="math inline">\(\log{\frac{p}{1-p}}\)</span> = -0.229153274 -0.114483595 * (<span class="math inline">\(race\_white\)</span>) - 0.244889178 * (<span class="math inline">\(Person.Gender\_Male\)</span>) + 1.038480834 * (<span class="math inline">\(Person.Gender\_Unknown\)</span>) + 0.652516293 * (<span class="math inline">\(Factors.Armed.Test\_unarmed\)</span>) - 0.004189227 * (<span class="math inline">\(Person.Age\)</span>)</p>
<p>where <span class="math inline">\(p\)</span> is the probability of a person being a perceived threat by the police, stating the incident as an “attack”</p>
<p>After fitting the logistic model and computing backwards elimination, we found the best model for our response variable <code>Factors.Threat.Level</code> to be an additive model between four explanatory variables: gender, race, armed status, and age. During backwards elimination, we fit several additive and interactive models using combinations of the four variables and determined which regression yielded the lowest AIC value. Therefore, whether or not a victim was perceived as a threat by police was best explained with an additive interaction between gender, race, armed status, and age.</p>
<p>We also investigated whether the proportion of people perceived as an “attack” threat level was different for victims of color versus white victims. We hypothesized that the proportion of POC who were perceived as an “attack” by police is significantly greater than the proportion of white victims perceived in the same threat level category. To investigate this hypothesis, we performed a <strong>hypothesis test</strong> using a significance level of <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p>(Note: For testing purposes, we assumed independence within our data set’s observations. In the context of this question, we will consider someone as a “POC” if they do not identify as “White.”)</p>
<p><span class="math inline">\(\pi_{POC}\)</span> = the proportion of people who were perceived as an “attack” by the police out of those shot who identify as a POC.</p>
<p><span class="math inline">\(\pi_{White}\)</span> = the proportion of people who were perceived as an “attack” by the police out of those shot who identify as White.</p>
<p><span class="math inline">\(H_0: \pi_{POC} = \pi_{White}\)</span></p>
<p>Null hypothesis: The proportion of people who were perceived as an “attack” by the police of those shot who identify as a POC is equal to the proportion of people who were perceived as an “attack” by the police of those shot who identify as white.</p>
<p><span class="math inline">\(H_A: \pi_{POC} &gt; \pi_{White}\)</span></p>
<p>Alternative hypothesis: The proportion of people who were perceived as an “attack” by the police of those shot who identify as a POC is greater than the proportion of people who were perceived as an “attack” by the police of those shot who identify as white.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'race'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   race [2]
  race  `Factors.Threat-Level`  props
  &lt;chr&gt; &lt;fct&gt;                   &lt;int&gt;
1 POC   attack                   1764
2 POC   not specified as attack  1010
3 White attack                   1912
4 White not specified as attack   955</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/hypothesis-race-pvalues-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1   0.995</code></pre>
</div>
</div>
<p><strong>Results</strong></p>
<p>Based on our summary statistics for the entire data set, we observed that the mean and median age of shooting victims are 35.4 and 34.0 years, respectively. Moreover, the standard deviation of this age range is 14.9 years, demonstrating the wide spread of data points included. We noticed a slight decrease in shootings per day in 2021 though the total range of average shootings per day was small and somewhat insignificant (from roughly 2.45 shootings to 2.8 shootings). When looking at the arms status of victims by gender, female victims were more likely to be armed than male victims. One reason for this is that male victims could have been seen as more aggressive and therefore more likely to become a victim no matter if they were armed. The age distribution of victims does not vary much between races. When we look at the different races in the count of total victims, we can see white victims and African American victims were most common. Close to 2962 of the victims were white; whereas, 1552 victims were black. If race had no impact on probability of being a victim, the proportions of victims by race would be similar as the US population by race. White Americans represent 0.578 of the population. African Americans make up 0.121 of the population.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  Person.Race          n
  &lt;chr&gt;            &lt;int&gt;
1 African American  1552
2 Asian              106
3 Hispanic          1081
4 Native American     91
5 Other               47
6 Unknown            730
7 White             2962</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4509058</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2362612</code></pre>
</div>
</div>
<p>White Americans represent 0.578 of the US population while they only represent 0.45 of the victims. African Americans make up 0.121 of the population while they present 0.236 of the victims.Therefore we can see that African American were targeted at a higher rate than white Americans.</p>
<p>The race with the most unarmed victims was black and the race with the least unarmed victims was Native American. Visualization can provide ample information on implicit bias and how race impacts the police’s approaches to interactions with different races. We also found the median age is roughly 34 years old for males and 35 years old for females. Male victims differ by their outliers, as many male victims are over the age of 75. The unknown victims appear to be significantly younger as seen by the median of ~21 years old.</p>
<p>We performed a hypothesis test to determine whether the proportion of people perceived as an “attack” threat level was different for victims of color versus white victims. Our hypothesis test yields a p-value of 0.995. Utilizing a significance level of 0.05, we fail to reject the null hypothesis that the proportion of people who were perceived as an “attack” by the police of those shot who identify as a POC is equal to the proportion of people who were perceived as an “attack” by the police of those shot who identify as white. As a p-value of 0.995 is greater than 0.05, we have weak evidence to support the alternative hypothesis that the proportion of people who were perceived as an “attack” by the police of those shot who identify as a POC is greater than the proportion of people who were perceived as an “attack” by the police of those shot who identify as white.</p>
<p><strong>Discussion and Limitations</strong></p>
<p>Our project allowed us to investigate how race, gender, age, and a civilian’s armed status affected perceived threat level in fatal police shootings across the US from 2015-2021. We hypothesized that male individuals who identify as a POC are perceived as an increased threat during fatal police shootings. Our statistical results do not support this hypothesis. After analyzing our data and results, we believe that our data is heavily impacted by bias and misconceptions, leading to unreliability in our results. Close to 2962 of the victims were white; whereas, 1552 victims were black. If race had no impact on probability of being a victim, the proportions of victims by race would be similar as the US population by race. White Americans represent 0.578 of the population. African Americans make up 0.121 of the population. White Americans represent 0.578 of the US population while they only represent 0.45 of the victims. African Americans make up 0.121 of the population while they present 0.236 of the victims.Therefore we can see that African American were targeted at a higher rate than white Americans. As seen by the map of fatal police shootings by state, the vast majority of shootings occurred in California. Therefore, the data is obviously includes location bias. This could affect our results as demographics change by state. Also, we believe that much of our data could be heavily impacted by bias, leading to unreliability. For example, every victim was labeled as mentally ill.&nbsp;This assumption created some concern for our team as we believed it was unlikely that every victim was mentally ill.&nbsp;Therefore, our results can support our specific data set but we do not believe that our results cannot be generalized upon a broader population beyond our sample. Further exploration can allow us to analyze the relationship between each state’s victims and demographics. By computing statistical analysis for each individual state and analyzing the perceived threat level, we can further our results and conclude how each state relates to our hypothesis. Also, with more data, we can analyze how socioeconomic levels relate to perceived threat level. This extra demographic will allow us to further our conclusion and visualize patterns between an individual’s socioeconomic level and their race, gender, age, and armed status. To better our analysis, we believe that more reliable and broad data would be beneficial to our results and validity. Because our data was collected by the CORGIS database through <em>The Washington Post</em>, our data could be very biased and invalid. By collecting data directly through the US or state governments, we believe our analysis will be more thorough and valid.</p>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>